- name: Deploy Meteor Instance to Provisioned Server
  hosts: all

  # Load configuration files.
  vars_files:
    - ../config.yml

  # Define tasks.
  tasks:
    - name: Build | Remove any old project sources.
      file:
        path: "/tmp/project"
        state: "absent"

    - name: Build | Remove any old project build destinations.
      file:
        path: "~/app"
        state: "absent"

    - name: Build | Checkout project source.
      git:
        repo: "{{ meteor_project_git }}"
        version: "{{ meteor_project_version }}"
        dest: "/tmp/project"
        clone: yes
        update: yes
        accept_hostkey: true

    - name: Build | Run build process.
      command: "/usr/local/bin/meteor build --directory ~/app --architecture {{ meteor_env_architecture }}"
      args:
        chdir: "/tmp/project"

    - name: Build | Remove project source.
      file:
        path: "/tmp/project"
        state: "absent"

    - name: Build | Install project dependencies.
      command: npm install
      args:
        chdir: "~/app/bundle/programs/server"
