- name: Deploy Meteor Instance to Provisioned Server
  hosts: all
  sudo: yes

  # Load configuration files.
  vars_files:
    ../vars/main.yml

  # Define tasks.
  tasks:
    - name: Meteor | Download project.
      unarchive: src={{ build_src }} dest={{ /var/www/meteor }} copy=no

    - name: Meteor | Install project dependencies.
      command: cd /var/www/meteor/bundle/programs/server && npm install

    - name: Meteor | Run Meteor on specified port.
      command: cd /var/www/meteor && {{ env_variables }} node main.js
