- name: Deploy Meteor Instance to Provisioned Server
  hosts: all
  sudo: yes

  # Load configuration files.
  vars_files:
    - ../vars/main.yml

  # Define tasks.
  tasks:
    - name: Build | Checkout project.
      git:
        repo: {{ meteor_project_git }}
        version: {{ meteor_project_version }}
        destination: "/tmp/project"

    - name: Build | Run build process.
      command: cd /tmp/project && /usr/local/bin/meteor build --directory /var/www

    - name: Build | Install project dependencies.
      command: cd /var/www/bundle/programs/server && npm install
