- name: Provision Meteor Server
  hosts: all
  sudo: yes

  # Load configuration files.
  vars_files:
    - ../config.yml

  # Define galaxy roles.
  roles:
    - geerlingguy.nodejs
    - carlos.acp.meteor

  # Define tasks.
  tasks:
    - name: Provision | Install g++.
      apt: pkg=g++ state=present
      sudo: yes

    - name: Provision | Install make.
      apt: pkg=make state=present
      sudo: yes

    - name: Provision | Install git.
      apt: pkg=git state=present
      sudo: yes
