- name: Run Meteor Application
  hosts: all

  # Load configuration files.
  vars_files:
    - ../config.yml

  # Define tasks.
  tasks:
    - name: Run | Map port 80 to specified Meteor run port.
      command: "iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port {{ meteor_port }}"
      sudo: yes

    - name: Run | Run the Meteor application.
      shell: "forever start main.js"
      environment: "{{ meteor_env_variables }}"
      args:
        chdir: "~/app/bundle"
